### ISSUE TITLE
R7: For technical fields (such as frameSize, bitDepth, frameRate), position the controlled vocabularies as recommendations of expression and not the definitive list.

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#10]
Many requests were to supplement existing controlled vocabularies with additional values for bitDepths, frameSizes and other technical specifications. The expression of these fields should be based on the nature of the instantiation rather than the contents of the picklist. (i.e. Saying "20 fps" (not on the list) is certainly better than saying "Other" which is on the list.)

**Comment by WeAreAVP** [comment]
Is this a schema issue?

**Comment by pdpinch** [comment]
It is now. 

Dave and I had a difference on opinion, but I've gone along with him and this has been added to the schema.

Begs the question, do we need a proposed CV?

**Comment by WeAreAVP** [comment]
ok, I'll look at the new version soon. For these fields I don't think CVs like bitDepth extra is that helpful. If an audio track is 32 bit or 4 bit or whatever odd number, then it shouldn't hinder the expression because it's not on the list. I'm thinking of Bruce Jacobs comments when value x, y, or z for a highly technical field isn't on the list.

**Comment by jackbrighton** [comment]
So, I'm hoping that all of these values in my own PBCore records are added to the records by machines, not people. In which case any suggested CV would be moot. But maybe that's just me. :)

**Comment by WeAreAVP** [comment]
Yeah I agree, about 80% of the elements within instantiation are handled much faster and more accurately by machines (for digital file-based content).
Peter, can you clarify what you meant? How would this issue be represented in the XSD?

**Comment by pdpinch** [comment]
CVs for these technical fields are now recommended and not required. 

We added an attribute, where appropriate, for units of measure.

I'm closing this issue.
