### ISSUE TITLE
R11: Allow support for multiple expressions of time-based descriptive metadata within a single asset records.

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#13]
Segmentation is used for a variety of purposes. For example, when logging a file, a cataloguer may want to note than a celebrity was featured from minute 2 to minute 4. For rights management, it might be necessary to understand that a still photograph was featured, for which there are no rights to distribute online. From the perspective of navigation, organizations might need to insert chapter points into a video.

It is important to be able to describe segments of an asset and relate those to the whole, rather than have to create new PBCore records for each segment (and have flimsy relationships between segments and assets).

**Comment by pdpinch** [comment]
Peter and Dave M are debating whether to add a startTime and endTime attribute to certain elements, or just recommending PBCore authors create multiple records with relationships. 

At the moment, Dave M is leaning towards using attributes.

**Comment by pdpinch** [comment]
in 3fcbe9d4de685c36301d3e1ab86c99b12ae06773, description has a type of descriptionStringType, which has startTime and endTime attributes. This allows descriptions to be segmented. 

However, this does not address segmentation of rights, which may be out of scope.

**Comment by kvanmalssen** [comment]
I like the solution of using descriptionStringType with startTime and endTime attributes.  Just not sure what segmentType means here.  I know this is a documentation issue, just wanted to make a note of it.

**Comment by jackbrighton** [comment]
I love the suggestion to allow (optional) startTime and endTime attributes to multiple elements. Seems like this could work for rightsSummary too without mucking up the works. It would work for subjects, contributors, and even coverage.

**Comment by MarcosSueiro** [comment]
I would again suggest ISO 8601 for this. It allows for start/end, start/duration and other formats; is machine readable; and it fits in just one field.
http://www.iso.org/iso/date_and_time_format

**Comment by jackbrighton** [comment]
Agreed!

**Comment by pdpinch** [comment]
We have written How To to go with the schema change.
