### ISSUE TITLE
R13: Allow support for inline XML (xsd:any) within extension, rights, and (maybe) description.

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#15]
Allow for possibility for PBCore to be transmitted with external standards (METSRights, ODRL, PREMIS, custom data, etc) expressed inline.

**Comment by pdpinch** [comment]
With version 5d0e20eabf4a35d9968d4d525d95f85f26990c45 the rightsSummaryType allows for an embeddedType now which can be used for inline XML. The Extension container has a extensionEmbedded element. 

With that same version there is also a linkType that allows for linking to an external rights expression.  

We have decided against inline XML for description.

**Comment by jackbrighton** [comment]
I think this is just fine.
