### ISSUE TITLE
R16: Updates to extension and annotation (and essenceTrack annotation) structure.

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#18]
Extension currently contains three discrete values (authority, type and value) within two fields. Also the extension can only contain key-value pairs and not hierarchical structures. Add third field extension and allow support for inline XML. Also since annotation is the extension of the instantiation, follow the same structure here as well.

**Comment by pdpinch** [comment]
with 5d0e20eabf4a35d9968d4d525d95f85f26990c45, broke extension into 3 elements: extensionType, extensionValue and extensionAuthorityUsed.

**Comment by jackbrighton** [comment]
I'd suggest doing this also for the annotation, because many people are interested in recording things like PREMIS metadata for a specific instantiation.
