### ISSUE TITLE
R17a: Remove semantically-meaningless ordering requirements for PBCore elements

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#19]
The schema should not require a particular sequence of element tags. This is unusual in my experience for schema, and I believe it unnecessarily increases the complexity of creating valid PBCore XML. I also don't see any upside to people who are writing PBCore parsers to have the tags in a particular order. I believe most parsers simply read the XML and create a data object which may no longer preserve the order.

**Comment by pdpinch** [comment]
we're not sure how to change this, in XML Schema.

**Comment by WeAreAVP** [comment]
i agree, I tested out doing this but a maxoccurs=unbounded gets in the way. I think it better to retract the request.

**Comment by WeAreAVP** [comment]
I vote to close this. Kara, any opinion?
