### ISSUE TITLE
R1a: For creator, contributor, and publisher provide support for management of (a) affiliation,

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#2]
a. Allow association of creators, contributor, or publishers with affiliated organizations (stations, companies, etc).

**Comment by pdpinch** [comment]
a. Planning to introduce a new string type with an affiliation attribute. Additionally, considering adding support for vCard.

**Comment by pdpinch** [comment]
In 3fcbe9d4de685c36301d3e1ab86c99b12ae06773 creator, contributor and publisher are of type affiliatedStringType which includes attributes for affilation, linkedID and annotation. 

I believe documentation should recommend that affiliation be a string, and linkedID be a URL for the affiliation or for a specific location defining the creator/contributor/publisher.

**Comment by WeAreAVP** [comment]
The affiliation attribute looks good. Though in this XML context it looks like the linkedID attribute should refer to the contributor and not the contributor@affiliation.
