### ISSUE TITLE
R17b: Additional adjust minOccurs to prevent semantically unclear expressions.

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#20]
PBCore currently allows confusing structural expressions such as <pbcoreContributor><contributorRole>Producers</contributorRole></pbcoreContributor> since many of the primary elements of the PBCore containers are not themslves required within the container (additionally the schema's comments and minOccurs statements frequently contradict each other on whether an element is required or not).

**Comment by pdpinch** [comment]
Need more specific recommendations.

**Comment by pdpinch** [comment]
The creator, contributor and publisher elements, within their respective containers, now have minOccurs="1" as of 3fcbe9d4de685c36301d3e1ab86c99b12ae06773

I believe this addresses the issue.

**Comment by jackbrighton** [comment]
Hold up a minute on this. You might not know who is the creator, contributor, or publisher so you'd have to leave them empty. For example an orphan work with no visible means of identifying any of these things. Or I might be the sole creator of a media asset, in which case there are no contributors. Or an asset might not yet be published, or even never published in which case there is no publisher. I don't see how it's confusing to leave these as minOccurs=0, and I believe making them mandatory will lead to worse confusion/frustration.
