### ISSUE TITLE
R18: Guide support for non-unique identifiers such as episode numbers, chapter numbers, series numbers, series identifiers, and other identifiers.

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#21]
Provide a formal structure for series of episodes - insuring that they remain linked together and not bound by series name.

Provide a formal structure for chapters within an episode - vital for web use. Each chapter must have separate meta-data, while the episode also can have the same meta-data structure.

**Comment by jackbrighton** [comment]
Isn't this solved by the use of pbcoreCollection and assetType?

**Comment by pdpinch** [comment]
As Jack suggests, this can be addressed by use of pbcoreCollection. We are working on a "How-To"
