### ISSUE TITLE
R21: Support subjectTypes (similar to MODS, MARC, and others)

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#24]
Allow distinction of the type of subject (whether geographical, topical, personal, etc).

**Comment by jackbrighton** [comment]
Hmmm, would this simply be a freeform text string 'type' attribute in <subject>, or a CV? Either way it could get unwieldy. I think this could be useful but I don't feel strongly about the need for it.

**Comment by MarcosSueiro** [comment]
Agreed --it seems like opening a whole can of worms.

**Comment by pdpinch** [comment]
We added an attribute "subjectType" to subject. There is a recommended CV.
