### ISSUE TITLE
R22: Allow or provide guidance on validatable expression of multiple PBCore assets within a single XML document/feed.

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#25]
Exchange of PBCore data between systems is complicated by lack of recommended methodology or means to package multiple assets into a single document or package (see MARCXML's collection element, modsCollection, atom, etc)

**Comment by pdpinch** [comment]
Plan to add a PBCoreCollection element at the top of the hierarchy. 

Also plan to recommend use of BagIt as an alternative.

**Comment by WeAreAVP** [comment]
It's good to see two options, either the PBCoreCollection element or bagit. The PBCore 2.0 draft 3 adds a 'PBCoreCollection' element; however the new 'PBCoreCollection' is the only permitted top-level element; thus a PBCore XML may not be written without the expression of a 'PBCoreCollection'. At one point we discussed allow either 'PBCoreDescriptionDocument' or 'PBCoreCollection' as the top level element (I remember Kara asking for allowance of 'pbcoreInstantiation' as an allowable top level element).

**Comment by pdpinch** [comment]
I didn't think that was technically allowed in XML Schema. If I'm wrong, can you propose the schema change?

**Comment by WeAreAVP** [comment]
Yeah, this is definitely allowed and well used in other comparable schemas. For instance see how mods accomplishes the same task: http://www.loc.gov/standards/mods/v3/mods-3-3.xsd.  The top level element may either be mods or modsCollection.

**Comment by MarcosSueiro** [comment]
The upcoming AES schema also uses something similar. 

Can this be accomplished by formalizing an "isPartOf" via an xLink between different assets, or is it too complicated?

http://www.w3.org/TR/xlink11/

**Comment by pdpinch** [comment]
We will publish an example use of pbcoreCollection.
