### ISSUE TITLE
R23: Allow complex coverage statements (as in PBCore 1.0)

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#26]
Allow expression of coverage to link expression of coverage, such as an expression of geospatial data with a human-readible geographical name, and a date that represents the coverage of that geographical area.

**Comment by pdpinch** [comment]
This issue needs more examples, possibly from NPR.

**Comment by jackbrighton** [comment]
Allowing attributes in <coverageType> could help with geospatial data at least. For example:

coverage> GEO:37.386013;-122.082932<coverage
coverageType format="RFC2426">spatial<coverageType

That might not be quite right but maybe close? And if so, we could do the same thing for temporal.

**Comment by pdpinch** [comment]
Thanks Jack. That's really close to what we ended up with. The only difference is we're using source and ref attributes on coverage instead of coverageType. 

Examples in the documentation at http://pbcore.org/v2/elements/pbcoreDescriptionDocument/pbcoreCoverage/coverage
