### ISSUE TITLE
R28a: Provide guidance and clarification on use of source and version attributes. 

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#32]
Better documentation to associate the Element Version and Namespace attributes from the PBCore data dictionary with their implementation in the source and version attributes. (Allow a version attribute at PBCoreDescriptionDocument as it is currently tough to figure out what version of PBCore a document is). (Consider using SKOS or publication dates to version PBCore's recommended picklists to encourage more consistent referenece with PBCore records).

**Comment by MarcosSueiro** [comment]
Does this need to be a separate element, or can it be embedded (as in one field being PBCore 1.0 or PBCore 1.2 or whatever)?

**Comment by pdpinch** [comment]
We've addressed this in documentation.

Source is the human-readable name of the authority.
Version is a numerical version number
Ref is a URI that (hopefully) identifies uniquely both source and version.

Throughout the documentation we have recommended controlled vocabularies, and include their URI's in sample documentation.
