### ISSUE TITLE
pbcoreAssetType

### ISSUE THREAD

**Issue by ghost** [WGBH/PBCore2.0#36]
Making a new thread on the new pbcoreAssetType container. The pbcoreAssetType element may repeat indefinately. Inside pbcoreAssetType the assetType field must occur only once while date may occur 0 to unlimited times.

Is there any meaning based on which pbcoreAssetType the date appears in. Such as:
        <pbcoreAssetType>
            <assetType>B-Roll</assetType>
            <date dateType="Date Created">2010-01-01</date>
            <date dateType="Date Cataloged">2010-01-02</date>
        </pbcoreAssetType>
        <pbcoreAssetType>
            <assetType>Stock Footage</assetType>
            <date dateType="Date Digitized">2010-01-03</date>
        </pbcoreAssetType>

Since the date reflect the pbcoreAssetType, here the digitization date is associated with the fact that it is 'stock footage' and the creation and cataloged dates are associated with the fact that it is 'b-roll'. My sense is that the placement of date with a certain pbcoreAssetType is meaningless, but it's in there for a reason.

Also a 'date' can not be expressed unless the 'assetType' is defined which seems like an unexpected dependency.

Should the pbcoreAssetType element be removed and the 'date' and 'assetType' moved up a level?

**Comment by kvanmalssen** [comment]
I agree, this is confusing.  I like having a date element at the Intellectual Content level, but not sure why it is contained within pbcoreAssetType.  Dave's example above is a good one.  What does the date digitized have to do with the fact that the asset is stock footage (and does date digitized even go here)?  And in turn, what does date cataloged have to do with the fact that it is b-roll?

Also, without very clear documentation here, people are going to be really confused about how different date elements should be used.  Already, there are so many potentially conflicting and/or unclear terms in the schema: Asset, Intellectual Content, Instantiation, Media Object.  Which is which? What date goes at what level?

Finally, I might be missing something here, but in the documentation for assetType it says, "The descriptor assetKind indicates the broad editorial format of the asset’s contents."  What is assetKind?  I don't see it used anywhere except in this definition.

**Comment by jackbrighton** [comment]
assetKind has gotta be a typo so that's easily fixed. I'm also still confused about assetType, but perhaps that could be clarified in documentation and further examples.

**Comment by dmaccarn** [comment]
assetType and assetDate more up a level and separated in new draft8.
