### ISSUE TITLE
use of sourceVersionGroup at instantiationIdentifierSource and genreAuthorityUsed?

### ISSUE THREAD

**Issue by ghost** [WGBH/PBCore2.0#39]
I'm trying to figure out the use of the sourceVersionStringType on a few of the classifying elements.
such as:

 &lt;instantiationIdentifierSource source="Some authority that made up the term NOLA Code" version="1.0"&gt;NOLA Code&lt;/instantiationIdentifierSource&gt;

or

 &lt;genreAuthorityUsed source="List naming convention at WGBH" version="1.1"&gt;PBCore Genre Authority List&lt;/genreAuthorityUsed&gt;

In cases like this, what should the source and version attributes be?

**Comment by WeAreAVP** [comment]
just noticed that while instantiationIdentifierSource is sourceVersionStringType, essenceTrackIdentifierSource is xsd:string. Should these be the same type?

**Comment by kvanmalssen** [comment]
Agreed, this is very confusing. In general, documentation is needed for all attributes, but especially those in sourceVersionStringType, since it is so widely used throughout the schema.

**Comment by pdpinch** [comment]
Moving Dave's 2nd comment to a new issue. 

Kara, we're working on documentation, but the effort couldn't begin until the XSD was (nearly) complete. If there's a particular ambiguity you are concerned about, please let us know.

**Comment by pdpinch** [comment]
Regarding the ambiguity between source and version attributes:

In (my) perfect world, source attributes would always be a URL that uniquely identifies both the source and the version of the CV term (if not a definition).

However, in the real world, we don't expect that level of specificity. So we imagine that source could be a string, like "PBS NOLA code" or a somewhat ambiguous URL like "http://metadata.pbsdigitallearninglibrary.org/definitions/titleType.html." We would encourage use of a version attribute to further specify, e.g. version="1.2" in the 2nd example. 

Does that help, or am I missing the point?

**Comment by WeAreAVP** [comment]
Thanks Peter this is helpful at figuring out if 'source' is supposed to respond to the semantic issues or document the authority of a term. Perhaps the placement of these attributes needs to some of the confusion. For instance with your example one could have:
identifier="ABCD 1234"
identifierSource="PBS NOLA Code"

but the source attribute here refers to the term "PBS NOLA Code" and not to "ABCD 1234" which is only an XSD string with no attribute. Thus I'm thinking in this case the 'source' attribute would be something around the source of the term "PBS NOLA Code" and not the identifier. Right?

**Comment by jackbrighton** [comment]
I'm with Peter if I understand what's he's saying here. The 'ref' attribute could come to the rescue here, for example:

identifier>ABCD 1234<identifier
identifierSource ref="http://nola.pbs.org/foo">PBS NOLA Code<identifierSource
