### ISSUE TITLE
R1c: For creator, contributor, and publisher provide support for management of (c) additional roles.

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#4]
c. PBCore limits expression of roles to one per creator, contributor, or publisher, although frequently one creator, contributor, or publisher performs more than one role to avoid entering a contributor multiple times to state all of their roles.

**Comment by pdpinch** [comment]
Change maxOccurs for creatorRole, contributorRole and publisherRole to "unbounded"

**Comment by pdpinch** [comment]
done as recommended, in 3fcbe9d4de685c36301d3e1ab86c99b12ae06773

**Comment by WeAreAVP** [comment]
This is great. Maybe Jack's Prairie Fire can finally be valid. I also see that creator, contributor and publisher are all now minOccurs=1 which is also really helpful. No more weird valid expressions like
<pbcoreContributor>
   <contributorRole>Producers</contributorRole>
</pbcoreContributor>
