### ISSUE TITLE
essenceTrackIdentifierSource should be of type sourceVersionStringType instead of xsd:string

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#40]
In another issue, avpreserve noted:

> just noticed that while instantiationIdentifierSource is sourceVersionStringType, 
> essenceTrackIdentifierSource is xsd:string. Should these be the same type?

**Comment by dmaccarn** [comment]
Do we need essenceTrackIdentifierSource? Most times, would it not be internal to the track list?

**Comment by MarcosSueiro** [comment]
I would vote to keep it, even though we have seldom used it.

**Comment by dmaccarn** [comment]
What if essenceTrackIdentifier included @source @version @annotation?
Would we still need essenceTrackIdentifierSource?

**Comment by MarcosSueiro** [comment]
Definitely not, although that seems overkill at first glance.
