### ISSUE TITLE
Do we still need subjectAuthorityUsed?

### ISSUE THREAD

**Issue by dmaccarn** [WGBH/PBCore2.0#41]
With the addition of @subjectType @source @version @annotation to "Subject", do we still need subjectAuthorityUsed?

**Comment by cmichael** [comment]
I would say no. Source=authority.

**Comment by MarcosSueiro** [comment]
Agreed.

**Comment by jackbrighton** [comment]
Right!

Is backwards compatibility an issue though?

**Comment by MarcosSueiro** [comment]
Always, in our case.
