### ISSUE TITLE
R6: Allow for multiple expressions of formatGenerations inside an instantiation.

### ISSUE THREAD

**Issue by pdpinch** [WGBH/PBCore2.0#9]
An instantiation may serve more than one role within a collection, such being both the 'Original' and the 'Preservation Master'.

**Comment by WeAreAVP** [comment]
PBCore 1.3's
<xsd:element maxOccurs="1" minOccurs="0" name="formatGenerations" type="pbcore.source.version.string">
was changed to
<xsd:element maxOccurs="unbounded" minOccurs="0" name="formatGenerations" type="sourceVersionStringType">
thus in cases where it is relevant, more than one generation value may be expressed per instantiation. Looks good.

**Comment by pdpinch** [comment]
Agreed.

**Comment by jackbrighton** [comment]
This looks done to me also.
